# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66f2ea85aa4b7d5ae9ae098fb08575bc64157cfd13215a7351ec5a49753afc28f53f22aaf4f02d7ee946f8873f4787e49a589ea34312ee50438ad4def271a0c1

test:
  secret_key_base: cb9e4216896cf84acc71d282aba8c770340cf4104e3328e9dac52e40489dabc3fcfe28ca0011650a681a11b281a588ae44079bfc25574418f3e317d1038662a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
